reloading configuration succeeded
reloading zones succeeded
all zones loaded
running
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
managed-keys-zone: Unable to fetch DNSKEY set '.': ncache nxrrset
resolver priming query complete
